### ISSUE TITLE
how to get data from multiple threads?

### ISSUE THREAD

**Issue by llogiq** [TyOverby/flame#11]
Currently, a thread-local library is used to collect frames. However, this fails when using multiple threads; the report will only ever contain frames for the thread that started the reporting. So how to report for multiple threads?

I think using a thread local library for _collection_ is the only viable choice (otherwise we'd synchronize cores and thus destroy the performance we intend to measure). Using this for multiple threads would probably require some kind of global library registry (where each thread local would need to be registered on construction, and would also require moving out of the thread on drop). Also we'd need a way to display data from multiple threads without thoroughly confusing users.

**Comment by TyOverby** [comment]
Yep, that's a good summary.  I have plans (and something of an implementation) for the data visualization aspect, but haven't really thought about an implementation yet.  Particularly, I don't want to incur any costs for any threads that don't use flame.

I'll do some prototypes when I get the time.

**Comment by TyOverby** [comment]
There is a `threads()` method that has been available for a while!
