### ISSUE TITLE
Update online docs?

### ISSUE THREAD

**Issue by DaseinPhaos** [TyOverby/flame#16]
I noticed that some methods in the [online doc](http://tyoverby.com/flame/flame/index.html) has been removed from the current published version of `flame`, for example the `dump_svg`. Also some newly added methods (`threads()` mentioned in #11 , e.g.) haven't been included there.

I tried to `cargo doc` the whole thing locally but it took extremely long time ( which I suspect was because of documenting some crate-dependencies of `thread_id`).

We do have the choice of fallback to reading source code directly though, but maybe it would be nice to update the online documentation? Is this the appropriate timing to do so, or should we be waiting for some further rounds of iterations?

**Comment by TyOverby** [comment]
Thanks for the report!  I've changed the link to point to docs.rs/flame which will always stay up to date!
