### ISSUE TITLE
Implement Stack Merging

### ISSUE THREAD

**Issue by behnam** [TyOverby/flame#19]
As noted on http://www.brendangregg.com/FlameGraphs/cpuflamegraphs.html#description

> The x-axis spans the sample population. It does not show the passing of time from left to right, as most graphs do. The left to right ordering has no meaning (it's sorted alphabetically to maximize frame merging).

Looks like rust flame is not doing any merging, which results in:
* technically not being a CPU Flame Graph;
* hard to see where the actual CPU usage is, as where the number of calls are high, the names don't fit in the small lines, and even the lines become invisible.
* too many SVG objects on the screen that slow down the rendering and digging in.

**Comment by behnam** [comment]
Example, from `unicode-bidi`: [flame-udhr-graph.html.zip](https://github.com/TyOverby/flame/files/1077343/flame-udhr-graph.html.zip)

**Comment by TyOverby** [comment]
This is because `flame` is a timeline flame graph, not an execution-percentage flame graph.

Instead of comparing `flame` to http://www.brendangregg.com/FlameGraphs/cpuflamegraphs.html#description, compare it to something like the Chrome profiler.

**Comment by TyOverby** [comment]
Right now the `flame` API is such that you can request all this data yourself and do stack merging yourself.

If I added an API that would allow you to export that data, would this be helpful?

**Comment by behnam** [comment]
Right. Yeah, on top level, I think would be great to have an export-to-html method that also merges the stacks.

**Comment by TyOverby** [comment]
Stack merging is a non-goal, but I'll add an API for dumping custom frames.

**Comment by TyOverby** [comment]
Issue filed here: https://github.com/TyOverby/flame/issues/20
