### ISSUE TITLE
Documentation / repo / crates.io mismatch

### ISSUE THREAD

**Issue by ticky** [TyOverby/flame#35]
The published documentation lists methods which do not exist in the latest version on Crates.io.

I also can’t find code in the repo which matches the documentation which is currently published.

Could you clarify what’s gone on here?

**Comment by TyOverby** [comment]
Crates.io says that the currently published version in 0.2.0 and docs.rs has the docs for 0.2.0

I don't publish from the repo with regularity, so keeping it updated with docs.rs or crates.io isn't a thing that is expected.

https://crates.io/crates/flame
https://docs.rs/flame/0.2.0/flame/

What methods are you not finding in the currently published version?

**Comment by ticky** [comment]
The documentation linked to by Crates.io is [this one](http://tyoverby.com/flame/flame/index.html), not the docs.rs version, which does appear to line up with the published version. Looks like this was changed in 272e11fbc8d53ef99ddc4ebc7b24b96a2ad116f3

**Comment by TyOverby** [comment]
Oh damn it.

**Comment by TyOverby** [comment]
https://crates.io/crates/flame

Updated

**Comment by ticky** [comment]
Thank you! 😃
