### ISSUE TITLE
flame::end(repl) attempted to end end

### ISSUE THREAD

**Issue by MasonRemaley** [TyOverby/flame#39]
I'm running into an issue where when I call `flame::start("repl")` and then later `flame::end("repl")` from one of my functions, the `end` call results in this panic:

```
error: thread 'main' panicked at 'flame::end(repl) attempted to end end'
```
I don't ever call start/end with "end" as an argument that I know of, unless [flamer](https://github.com/llogiq/flamer) is doing that for some reason. When I have a few minutes to kill I'm gonna go through my project and comment out all of the start/end calls until I find the minimal repro case, but I figured I'd post here in the meantime in case anyone else has any intuition about what would cause this.

**Comment by MasonRemaley** [comment]
> I don't ever call start/end with "end" as an argument [...]

This turned out to be false--due to a copy paste error I was calling `flame::start("end")` and somehow missed it when searching my code for `start("end")`. Fixed that and now everything works as expected.

Sorry for the quick open/self-resolve, but thanks for the great library!

**Comment by TyOverby** [comment]
:+1: Glad you got things figured out!
