### ISSUE TITLE
feature request: end_with API

### ISSUE THREAD

**Issue by llogiq** [TyOverby/flame#8]
To allow easy insertion of frames without having to rely on the guard interface, having a method like `flame::end_with<T>(frame: &str, result: T) -> T` could make insertion on exit easier. Otherwise we'd have to create a temporary to store a return value.

**Comment by TyOverby** [comment]
This could be useful, especially for code-generation like flamer.

I can add this at the end of the day today, but if you'd like it sooner, feel free to open up a PR.  I've also sent you an invitation to be a maintainer to FLAME, so if you're interested, you could merge your PR yourself!
